### ISSUE TITLE
Custom validators support

### ISSUE THREAD

**Issue by zbicin** [sagrawal14/bootstrap-angular-validation#13]
I though it'd be cool if one would be able to add his own validator support to the module, e.g. something like this:

``` javascript
        .config(['bsValidationConfigProvider', (bsValidationConfigProvider) => {
            var messages = {
                myCustomValidator: 'My custom validator says your input is invalid'
            };

            angular.extend(bsValidationConfigProvider.global.messages, messages);

           bsValidationConfigProvider.global.customValidators = ['myCustomValidator'];
        }])
```

**Comment by andy-22** [comment]
I also have a problem with my custom validators. I have implemented directive for custom validation and I don't know how to display the error message for that directive. Any help is appreciated.

**Comment by sagrawal31** [comment]
Can you show your directive (only validation part) where you are adding the custom validation? Most probably if you are adding a custom validation using [`ngModelController.$validators`](https://docs.angularjs.org/api/ng/type/ngModel.NgModelController#$validators) then you can use the key you are adding to the `$validators` to your input element like `myxyzkey-notification="This is the custom error message"`.

**Comment by andy-22** [comment]
Shashank,

Here is my directive:

'use strict';
angular.module('InvestmentModule')
    .directive('validateMustEqualToOrGreater', function () {
        return {
            // restrict to an attribute type.
            restrict: 'A',

```
        // element must have ng-model attribute.
        require: 'ngModel',
        // scope = the parent scope
        // element = the element the directive is on
        // attrs = a dictionary of attributes on the element
        // ngModel = the controller for ngModel.
        link: function (scope, element, attrs, ngModel) {
                function isEqualToOther(modelValue) {

                    var isEqualOrGreater = false;

                   var comparedValue = attrs.validateMustEqualToOrGreater;


                    if(!modelValue || !comparedValue){
                        // It's valid because we have nothing to
```

compare against
                            return true;
                        }

//console.log(parseFloat(comparedValue.replace(/,/g, '')).toFixed(2) +
"              "+ parseFloat(modelValue.replace(/,/g,
'')).toFixed(2));
                    var isEqualOrGreater =
(parseFloat(modelValue.replace(/,/g, '')).toFixed(2) >=
parseFloat(comparedValue.replace(/,/g, '')).toFixed(2));
                    return isEqualOrGreater;
                }

```
            ngModel.$validators.notEqualTo = function (modelValue) {
                return isEqualToOther(modelValue);
            };
        }
    };
});
```

and here is how I use it:

<div class="form-group required">
                    <label for="matured_amount" class="control-label
col-xs-4">Maturity Amount</label>
                    <div class="col-xs-8">
                        <input type="text"
                               class="form-control"
                               id="matured_amount"
                               name="matured_amount"
                               placeholder="Maturity Amount"
                               ng-model="matured_amount"
ng-pattern="/^[0-9][0-9\,]*(\.\d{1,2})?$|^\$?[\.]([\d][\d]?)$/"
validate-must-equal-to-or-greater="{{original_amount}}"
                               required-notification="Maturity Amount
is required"
                               pattern-notification="Maturity Amount
is invalid. Only Numbers, comma[,] and period[.] are allowed"
validate-must-equal-to-or-greater-notification="Maturity Amount Can
not be less than Investment Amount"
                               required>
                    </div>

```
            </div>
```

Thanks a lot for your help.

**Comment by sagrawal31** [comment]
@andy-22 Like I mentioned in the above comment, you can just use the validation key suffixed with `-notification`. So in this case, you just have to use

``` html
notEqualTo-notification="Maturity Amount Can not be less than Investment Amount"
```

instead of

``` html
validate-must-equal-to-or-greater-notification="Maturity Amount Can not be less than Investment Amount"
```

Remember, it's not the name of the directive but the name of the `$validators` key you are adding in your directive.

**Comment by ShaneYu** [comment]
@sagrawal14 I'd close this one too, this is very old and I think you covered everything in the original issues content.

**Comment by sagrawal31** [comment]
@zbicin I think this is no longer an issue. Closing this. Feel free to open it again!
