### ISSUE TITLE
Add default message and warning for custom validation with no message

### ISSUE THREAD

**Issue by sagrawal31** [sagrawal14/bootstrap-angular-validation#14]

**Comment by sagrawal31** [comment]
[andy-22 commented 5 days ago](https://github.com/sagrawal14/bootstrap-angular-validation/issues/13#issuecomment-244215501)

I also have a problem with my custom validators. I have implemented directive for custom validation and I don't know how to display the error message for that directive. Any help is appreciated.

**Comment by sagrawal31** [comment]
[sagrawal14 commented 12 hours ago](https://github.com/sagrawal14/bootstrap-angular-validation/issues/13#issuecomment-244848121)

Can you show your directive (only validation part) where you are adding the custom validation? Most probably if you are adding a custom validation using ngModelController.$validators then you can use the key you are adding to the $validators to your input element like myxyzkey-notification="This is the custom error message".

**Comment by sagrawal31** [comment]
[andy-22 commented 3 hours ago](https://github.com/sagrawal14/bootstrap-angular-validation/issues/13#issuecomment-244953353)

Shashank,

Here is my directive:

'use strict';
angular.module('InvestmentModule')
    .directive('validateMustEqualToOrGreater', function () {
        return {
            // restrict to an attribute type.
            restrict: 'A',

```
        // element must have ng-model attribute.
        require: 'ngModel',
        // scope = the parent scope
        // element = the element the directive is on
        // attrs = a dictionary of attributes on the element
        // ngModel = the controller for ngModel.
        link: function (scope, element, attrs, ngModel) {
                function isEqualToOther(modelValue) {

                    var isEqualOrGreater = false;

                   var comparedValue = attrs.validateMustEqualToOrGreater;


                    if(!modelValue || !comparedValue){
                        // It's valid because we have nothing to
```

compare against
                            return true;
                        }

//console.log(parseFloat(comparedValue.replace(/,/g, '')).toFixed(2) +
"              "+ parseFloat(modelValue.replace(/,/g,
'')).toFixed(2));
                    var isEqualOrGreater =
(parseFloat(modelValue.replace(/,/g, '')).toFixed(2) >=
parseFloat(comparedValue.replace(/,/g, '')).toFixed(2));
                    return isEqualOrGreater;
                }

```
            ngModel.$validators.notEqualTo = function (modelValue) {
                return isEqualToOther(modelValue);
            };
        }
    };
});
```

and here is how I use it:

<div class="form-group required">
                    <label for="matured_amount" class="control-label
col-xs-4">Maturity Amount</label>
                    <div class="col-xs-8">
                        <input type="text"
                               class="form-control"
                               id="matured_amount"
                               name="matured_amount"
                               placeholder="Maturity Amount"
                               ng-model="matured_amount"
ng-pattern="/^[0-9][0-9\,]*(\.\d{1,2})?$|^\$?[\.]([\d][\d]?)$/"
validate-must-equal-to-or-greater="{{original_amount}}"
                               required-notification="Maturity Amount
is required"
                               pattern-notification="Maturity Amount
is invalid. Only Numbers, comma[,] and period[.] are allowed"
validate-must-equal-to-or-greater-notification="Maturity Amount Can
not be less than Investment Amount"
                               required>
                    </div>

```
            </div>
```

Thanks a lot for your help.

**Comment by sagrawal31** [comment]
[sagrawal14 commented 19 minutes ago](https://github.com/sagrawal14/bootstrap-angular-validation/issues/13#issuecomment-245005060)

@andy-22 Like I mentioned in the above comment, you can just use the validation key suffixed with -notification. So in this case, you just have to use

notEqualTo-notification="Maturity Amount Can not be less than Investment Amount"
instead of

validate-must-equal-to-or-greater-notification="Maturity Amount Can not be less than Investment Amount"
Remember, it's not the name of the directive but the name of the $validators key you are adding in your directive.

**Comment by sagrawal31** [comment]
@andy-22 Moved your's problem as a separate issue. Although it was not an issue if you add the notification attribute but it was throwing an exception if there was no message for a validation error. 

So fixed that and added a warning for that as well. 
![image](https://cloud.githubusercontent.com/assets/1804514/18282593/65f1327c-747f-11e6-95c1-0a0f27f2b672.png)

**Comment by andy-22** [comment]
Thanks Shashank,
I will grab the latest code and try it out.

Andy

**Comment by andy-22** [comment]
Shashank,
I grabbed the latest through bower and now I get the attached error
