### ISSUE TITLE
required attribute with expression

### ISSUE THREAD

**Issue by vijaykrrao** [sagrawal14/bootstrap-angular-validation#19]
Hi Shasshank,

I have situation where the input field needs to made mandatory based on a condition. My html is as below:

` <div class="form-group">
       <label for="inputPO" class="control-label">PO Number:</label>
       <input type="text" id="inputPO" class="form-control" name="po" maxlength="10"
                     ng-model="invoice.PO" required**="isPORequired"**>
   </div>
`
Notice the 'required' attribute has a binding to scope object/variable. if isPORequired is set to 'true' only then it should validate.

Can this be achieved? Appreciate your input.

Thanks & Regards.

**Comment by sagrawal31** [comment]
Hi, @vijaykrrao. According to the HTML5 spec, it doesn't matter what you pass to the `required` attribute value, the input field will be mandatory as long as it has the `required` attribute. So even if your scope variable `isPORequired` is `false`, there is still the `required` attribute present in that input element.

Consider using the Angular's inbuilt [ng-required](https://docs.angularjs.org/api/ng/directive/ngRequired) attribute which dynamically add the required to your input element based on your expression.

```
<input type="text" id="inputPO" class="form-control" name="po" maxlength="10"
    ng-model="invoice.PO" ng-required="isPORequired">
```

**Comment by ShaneYu** [comment]
@sagrawal14 I'd close this one off, you are correct and that he should be using the `ng-required` attribute instead.

**Comment by shanoy** [comment]
Hi, @sagrawal14 Does work this validator with angular-ui-select directive? Thanks for reply!

**Comment by sagrawal31** [comment]
Hi @shanoy sorry for the late reply. Yes, this will work with any validator out of the box.
