### ISSUE TITLE
Ability to distinguish between has-error and required

### ISSUE THREAD

**Issue by ry8806** [sagrawal14/bootstrap-angular-validation#21]
Hello,

I was wondering if there was a way (using your module) to distinguish between when something is "error" or "required"??

If not, but you'd welcome this functionality, I'd be happy to implement it and send a PR.

As a future advancement (if the above is approved) I think it would be good if you could specify a "genericValidator" and then explicitly give it a class to put on the form-group element. E.g. min = "has-min" which would allow users to style the form-group element differently depending on the "type" of validation failure

Thanks, Ryan

**Comment by sagrawal31** [comment]
Hmmm..quite a nice feature for this module. This will help styling the input fields differently. I'll implement in a few days.

**Comment by ry8806** [comment]
thanks for your quick response, I don't mind helping out if you need?

**Comment by sagrawal31** [comment]
Yeah, sure. It would be great if you can submit a PR. It will be appreciated. I could have done it right away but I'm quite busy in my sister's wedding.

**Comment by ry8806** [comment]
created PR #22 - to begin tracking this and looking at the best way to implement with the current library

when you're free, let me know what your initial thoughts are

...enjoy the wedding

**Comment by sagrawal31** [comment]
Amazing. I'll look at it asap

**Comment by sagrawal31** [comment]
@ry8806 wait! I actually had a glimpse in my mind when you raised this issue that Angular do this on its own but somehow I skipped that and worked on your PR #22 for an hour. But I went back and checked that and I was correct. Angular adds the classes based on the validation keys.

For example, if a field has two validations `min` & `max` and when any of them fails, it will add a `ng-invalid-min` or `ng-invalid-max` class and removes them when validation passes. Is that what you want?

**Comment by sagrawal31** [comment]
Oh! I read your description again. You want the classes on the `form-group` class. Never mind

**Comment by sagrawal31** [comment]
@ry8806 Now on any error, the library will add classes on the `.form-group` element. The prefix of the class is `bs-has-error-` to keep it simple and avoid collision. It will append the name/key of the validation. For example, `.bs-has-error-required`, `.bs-has-error-min` or `.bs-has-error-email` etc.
