### ISSUE TITLE
Include non-minificated sources in bower package

### ISSUE THREAD

**Issue by vip9** [sagrawal14/bootstrap-angular-validation#28]
When using main-bower-files, the .min.js file is omitted for automated injecting of deps.

**Comment by sagrawal31** [comment]
@vip9 Is this what you wanted https://github.com/sagrawal14/bootstrap-angular-validation/commit/942151d0981a6737a66c14e2ef2c4458face9eb1?

**Comment by vip9** [comment]
I suppose yes, thank you. When developing, that would be great of having also beautified and not mangled output too.

**Comment by kaoz70** [comment]
Hello, when using bower install, I am still getting only the .min files, can you make the unminified files available too?
