### ISSUE TITLE
Styleguide

### ISSUE THREAD

**Issue by julianbei** [sagrawal14/bootstrap-angular-validation#6]
I would like to recommend you to read the Airbnb Javascript styleguide: https://github.com/airbnb/javascript

afterwards I would like to refactor the code to match that style.

If you are programming with atom, there is a nice plugin which is https://atom.io/packages/linter-jscs.
This plugin fixes a lot of stuff automagically.

Even if Jscs is outdated and no longer maintained, I would suggest you to use this atom plugin it really makes your life easier.

even though you might want to use the  eslint linter instead of jshint.
For both linters is a styleguide available at: https://github.com/airbnb/javascript/tree/master/linters

Coding style is not only a matter of taste but also crucial for Open Source commitment, reusability and maintainability.

**Comment by sagrawal31** [comment]
Thanks for sharing this style guide @julianbei. I always tried to follow a common pattern across my projects but I was not aware of that many peoples are using this style guide that you shared. I've gone through it for ES5 style guide and I'll refactor the code accordingly. Thanks
